# Generated by Django 4.2.24 on 2025-09-26 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='total_points',
        ),
    ]
