# Generated by Django 4.2.24 on 2025-09-26 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_competition_total_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='pointrule',
            name='prem_ball',
            field=models.FloatField(default=1.0, help_text='Premiu )'),
        ),
        migrations.AddField(
            model_name='pointrule',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.competition'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='total_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='participant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user'),
        ),
        migrations.AlterField(
            model_name='point',
            name='reason',
            field=models.CharField(choices=[('referral', 'Referral'), ('channel_join', 'Join All Channels'), ('premium_referral', 'Premium Referral'), ('task_instagram', 'Instagram Task'), ('daily_bonus', 'Daily Bonus')], max_length=50),
        ),
        migrations.AlterField(
            model_name='pointrule',
            name='action_type',
            field=models.CharField(choices=[('referral', 'Referral'), ('channel_join', 'Join All Channels'), ('premium_referral', 'Premium Referral'), ('task_instagram', 'Instagram Task'), ('daily_bonus', 'Daily Bonus')], default='referral', max_length=50),
        ),
        migrations.AlterField(
            model_name='pointrule',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.competition'),
        ),
        migrations.AlterField(
            model_name='pointrule',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='pointrule',
            unique_together={('competition', 'action_type')},
        ),
        migrations.RemoveField(
            model_name='pointrule',
            name='multiplier',
        ),
    ]
