# Generated by Django 5.2.6 on 2025-09-24 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='points_earned',
        ),
        migrations.RemoveField(
            model_name='point',
            name='total_balance',
        ),
        migrations.AddField(
            model_name='point',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='point',
            name='points',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='channel',
            name='type',
            field=models.CharField(choices=[('channel', 'Channel'), ('group', 'Group')], default='channel', max_length=20),
        ),
        migrations.AlterField(
            model_name='competition',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('finished', 'Finished')], default='active', max_length=30),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='point',
            name='event_type',
            field=models.CharField(choices=[('referral', 'Referral'), ('task_completion', 'Task Completion'), ('bonus', 'Bonus')], default='referral', max_length=30),
        ),
    ]
